[build]
builder = "DOCKERFILE"
dockerfilePath = "mysql57-service/Dockerfile"

[deploy]
startCommand = "docker-entrypoint.sh mysqld"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
